[versions]
# plugins
kotlin = "2.3.0"
agp = "8.13.2"
# room compiler で使用。
# ksp のバージョンは、kotlin_version と同じ世代のものを指定する必要がある。
# https://github.com/google/ksp/releases で確認する。
ksp = "2.3.4"

# libraries
androidUtilitiesVersion = "4.12.0"
androidBinding = "1.12.1"
androidServer = "2.0.1"
androidViewex = "1.1.19"
androidDialog = "6.3.4"
androidWorker = "2.2.9"
androidMediaPlayer = "4.3.1"
androidMediaProcessor = "4.2.0"
androidMediaEditor = "0.3.1"
cameraCore = "1.5.2"
concurrentFuturesKtx = "1.3.0"
gridlayout = "1.1.0"
gson = "2.13.2"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleViewmodelKtx = "2.10.0"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
okhttp = "5.3.2"
preferenceKtx = "1.2.1"
roomRuntime = "2.8.4"
roomCompiler = "2.8.4"
coroutinesCore = "1.10.2"

[libraries]
android-dialog = { module = "com.github.toyota-m2k:android-dialog", version.ref = "androidDialog" }
android-viewex = { module = "com.github.toyota-m2k:android-viewex", version.ref = "androidViewex" }
android-binding = { module = "com.github.toyota-m2k:android-binding", version.ref = "androidBinding" }
android-utilities = { module = "com.github.toyota-m2k:android-utilities", version.ref = "androidUtilitiesVersion" }
android-media-player = { module = "com.github.toyota-m2k:android-media-player", version.ref = "androidMediaPlayer" }
android-media-editor = { module = "com.github.toyota-m2k:android-media-editor", version.ref = "androidMediaEditor" }
android-server = { module = "com.github.toyota-m2k:android-server", version.ref = "androidServer" }
android-media-processor = { module = "com.github.toyota-m2k:android-media-processor", version.ref = "androidMediaProcessor" }
android-worker = { module = "com.github.toyota-m2k:android-worker", version.ref = "androidWorker" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraCore" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
androidx-camera-video = { module = "androidx.camera:camera-video", version.ref = "cameraCore" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
#androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
#androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
kotrinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
devtool-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

